#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          infopoint-html
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop InfoPoint HTML viewer
### END INIT INFO

# TODO stopping: get PID and write it to /var/run
# TODO what if another X server is running?

case "$1" in
  start)
    # start app from ~/.xinitrc
    su vertretungsplan -c xinit &
    ;;
  stop|restart|force-reload)
    echo "not yet implemented."
    ;;
esac;

