#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          infopoint-html
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop InfoPoint HTML viewer
### END INIT INFO

# default config
. /etc/default/infopoint-html

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

# TODO stopping: get PID and write it to /var/run
# TODO what if another X server is running?

case "$1" in
  start)
    if [ "$START" != "yes" ]; then
      log_warning_msg "Not starting infopoint-html, it is disabled in /etc/default/infopoint-html";
      return 0;
    fi

    # start app from ~/.xinitrc
    su infopoint-html -c xinit &
    ;;
  stop|restart|force-reload)
    echo "not yet implemented."
    ;;
esac;

