#!/bin/sh -e
# TODO also use debconf for this
if [ -z "`grep 'allowed_users=anybody' /etc/X11/Xwrapper.config`" ]; then
  echo "allowed_users=anybody" >> /etc/X11/Xwrapper.config
fi;

if [ -z "`grep infopoint-html /etc/passwd`" ]; then
# TODO need a shell?
  useradd -ms /bin/bash infopoint-html
fi;

if [ -f ~infopoint-html/.xinitrc ]; then
  rm -f ~infopoint-html/.xinitrc;
fi;
ln -s /usr/share/infopoint-html/xinitrc ~infopoint-html/.xinitrc

#DEBHELPER#
