#!/bin/sh
# simple wrapper for xulrunner

if [ -r /etc/default/infopoint-html ]; then
  . /etc/default/infopoint-html;
fi;

if [ "$#" -gt 0 ]; then
  xulrunner-1.9.1 /usr/share/infopoint-html/application.ini $@;
else
  xulrunner-1.9.1 /usr/share/infopoint-html/application.ini $URL;
fi

