#!/bin/sh
# simple wrapper for xulrunner

if [ -z "$DISPLAY" ]; then
  echo "Error: no X server found. (\$DISPLAY is not set)"
  exit 1
fi

# we want the screen to be on always
xset -dpms
xset s noblank
xset s off
setxkbmap -option terminate:ctrl_alt_bksp

if [ -r /etc/default/infopoint-html ]; then
  . /etc/default/infopoint-html;
fi;

# look for xulrunner, newest first
XULRUNNER=
for xrapp in xulrunner xulrunner-`seq -s '.0 xulrunner-' 25 -1 10`.0 \
             xulrunner-1.9.2 xulrunner-1.9.1 xulrunner-1.9; do
  if [ -n "`which $xrapp`" ]; then
    XULRUNNER=`which $xrapp`
    break
  fi
done

if [ -z "$XULRUNNER" ]; then
  echo "Could not find a supported xulrunner instance."
  exit 1
fi

# look if we were installed somewhere or run locally
BASEDIR=`dirname $0`
APPDIR=
for dir in /usr/local/share/infopoint-html /usr/share/infopoint-html \
           $BASEDIR/xul; do
  if [ -f "$dir/application.ini" ]; then
    APPDIR=$dir
    break
  fi
done
if [ -z "$APPDIR" ] ; then
  echo "Something went wrong, I could not find my application.ini :(";
  exit 1
fi

echo starting with $XULRUNNER from $APPDIR...
if [ "$#" -gt 0 ]; then
  $XULRUNNER $APPDIR/application.ini $@;
else
  $XULRUNNER $APPDIR/application.ini $URL;
fi

