#!/bin/sh
# simple wrapper for xulrunner

if [ -r /etc/default/infopoint-html ]; then
  . /etc/default/infopoint-html;
fi;

# look for xulrunner
XULRUNNER=
for xrapp in "xulrunner xulrunner-1.9 xulrunner-1.9.1 xulrunner-1.9.2 xulrunner-10.0"; do
  if [ -n "`which $xrapp`" ]; then
    XULRUNNER=`which $xrapp`
    break
  fi
done

if [ "$#" -gt 0 ]; then
  $XULRUNNER /usr/share/infopoint-html/application.ini $@;
else
  $XULRUNNER /usr/share/infopoint-html/application.ini $URL;
fi

